프로젝트 구조
f-lab-edu/my-crowd-funding pull request #1
Opened 2024-01-11 14:22 UTC by minjinJeong

### 변경 사항
헥사고날 아키텍처를 참고하여 프로젝트 구조를 만들어 보았습니다.

### 프로젝트 구조
- 크게 계층별로 묶었습니다.
- 사용 예시를 위해 회원 관련 코드를 초안 작성했습니다.
- 도메인 계층의 Service에 InputPort를 자동 주입해주기 위해 UseCase 어노테이션을 정의했습니다.
- 도메인 계층에서 lombok 라이브러리만을 사용했습니다.

2024-01-16 14:28 UTC, f-lab-justin requested changes
@ieunji2 
한번 살펴보셔요~!

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/MemberPersistenceAdapter.java
> +        return null;
@minjinJeong 
Exception을 던져놓으면 까먹지 않고 구현할 수 있습니다! 
// @TODO 같은 걸 달아놓으시면 ide에서 모음으로 확인할 수도 있습니다.

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/entity/MemberEntity.java
> +    BigInteger userId;
@minjinJeong 
private 접근자을 넣어보면 좋을 것 같습니다. 
그리고 PK를 설정하는 annotation도 한번 살펴보세요!
table이름 챙겨보세요~! 
@Table("members")
public class MemberEntity {
} 

member.memberId가 아니라 member.id
```
@Column("member_id")
Long id
```

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/entity/MemberEntity.java
> +    String linkType;
@minjinJeong
enum -> string으로 저장하게 하는 방법을 한번 살펴보세요!
type, code 등은 enum클래스를 사용해서 정리해놓는 것이 편리하고 확장성도 좋습니다. 

```
switch(linkType) {
   case Click: 
   case Push: 
}
```

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/model/Member.java
> +@Setter
@minjinJeong 
Getter, Setter를 열어주는 것은 어떤 단점이 있을까요??

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/model/Member.java
> +    private char gender;
@minjinJeong 
gender도 enum값을 쓰는 것이 좋습니다~!

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/model/Member.java
> +    private String birthDay;
@minjinJeong 
day같은 경우도 date나 포맷을 테스트할 수 있는 타입을 지정해서 사용하시면 문제를 일찍 발견할 수 있고, 다양한 함수를 사용할 수 있어서 유용합니다.

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/service/MemberService.java
> +        return member;
@minjinJeong 
```java
@Override
public Member createMember(Member member) {
    return memberPort.saveMember(
       member.activate()
    );
}
```

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/input/rest/MemberRestAdapter.java
> +    ResponseEntity<MemberCreateResponse> createMember(@RequestBody MemberCreateRequest request) {
@ieunji2 
messageConverter 설정도 한번 살펴보세요~!

```java
MemberCreateResponse createMember(@RequestBody MemberCreateRequest request) { 
   return memberMapper.toMemberCreate(member);
}
```

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/application/ports/output/MemberPort.java
> +    Optional<Member> getMemberByKey(String userKey);
@ieunji2 
getMemberByUserKey(String userKey);

```java
memberPort.getMemberByUserKey(String userKey);
```

2024-01-16 14:28 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/model/MemberStatus.java
> +    }
@minjinJeong 
```java
public static MemberStatus valueOf(String status) {
    // status로 enum값을 만드는 로직.
    return MemberStatus;
}

MemberStatus status = MemberStatus.valueOf("10");
```

2024-01-19 13:18 UTC, f-lab-justin approved these changes
@minjinJeong 
고생하셨습니다! 쭉쭉 가보시죠!

2024-01-23 14:29 UTC, f-lab-justin approved these changes
@minjinJeong
머징 가시지요!!

2024-01-23 14:29 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/service/MemberService.java
> +public class MemberService implements CreateMemberUseCase, UpdateMemberUseCase, GetMemberUseCase {
@minjinJeong

CreateMemberUseCase, UpdateMemberUseCase, GetMemberUseCase 
-> 
RegistMemberUseCase, DeregistMemberUseCase, LoginUseCase,

2024-01-23 14:29 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/input/data/request/MemberCreateRequest.java
> +    private String linkType;
@minjinJeong
linkType은 enum이겠죠?

2024-01-23 14:29 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/entity/MemberEntity.java
> +    @Column(name = "user_key")
@minjinJeong
요 부분은 생략 가능합니다~ 한번 살펴보셔요~!

2024-01-24 16:11 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/MemberPersistenceAdapter.java
> +        return null;
주석 추가 및 Exception을 던지도록 수정했습니다.

```
// TODO : modify method after make api docs
@Override
public Member saveMember(Member member) {
  throw new NullPointerException();
}
```

2024-01-24 16:14 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/entity/MemberEntity.java
> +    BigInteger userId;
JPA Entity에서 제공하는 어노테이션을 이용해 PK 설정 및 table 이름 등을 설정했습니다.
- 컬럼 id 는 DB에서는 member_id이므로, @Column으로 name 설정
- PK에 기본키 생성 설정

```
@Entity
@Table(name = "user")
public class MemberEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long id;
}
```

2024-01-24 16:16 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/entity/MemberEntity.java
> +    String linkType;
성별이나 Type, Status 등을 Enum으로 분리했습니다.
- MemberStatus, MemberLinkType, MemberGender
- @Converter를 사용해 Entity에 Enum <> DB 매핑 컨버터를 추가

2024-01-24 16:30 UTC, minjinJeong commented on src/main/java/com/flab/funding/domain/model/Member.java
> +@Setter
Getter와 Setter를 열어주면,
1. 변수를 private 으로 선언하더라도 구현을 외부로 노출하게 됩니다. (캡슐화 위반)
2. get/set의 접두사는 단순히 데이터를 저장하거나 꺼내는 것을 목표로 합니다.
  > 데이터가 아닌, 행위(도메인)을 표현하도록 메소드를 만들어야 합니다.

따라서 @Getter와 @Setter를 제거하고 필요 시 activate()와 같이 행위를 표현하는 메서드를 추가했습니다.

2024-01-24 16:32 UTC, minjinJeong commented on src/main/java/com/flab/funding/domain/model/Member.java
> +    private char gender;
MemberGender Enum을 추가했습니다.

2024-01-24 16:33 UTC, minjinJeong commented on src/main/java/com/flab/funding/domain/model/Member.java
> +    private String birthDay;
생일 같은 경우 LocalDate를, 생성일자 같은 경우 LocalDateTime 으로 수정했습니다.

2024-01-24 16:36 UTC, minjinJeong commented on src/main/java/com/flab/funding/domain/service/MemberService.java
> +        return member;
Setter를 제거하며 회원 상태를 설정하는 로직을 내부로 숨기고, 한 줄로 간결하게 표현하도록 수정했습니다.

2024-01-24 16:41 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/input/rest/MemberRestAdapter.java
> +    ResponseEntity<MemberCreateResponse> createMember(@RequestBody MemberCreateRequest request) {
HTTP 메시지 컨버터를 사용하여, @ResponseBody를 붙였습니다.
- 반환값이 객체일 경우, json으로 반환

```
    @PostMapping("/member")
    @ResponseBody
    MemberCreateResponse createMember(@RequestBody MemberCreateRequest request) {
         Member member = memberService.registMember(memberMapper.toMember(request));
         return memberMapper.toMemberCreateResponse(member);
    }
```

2024-01-24 16:42 UTC, minjinJeong commented on src/main/java/com/flab/funding/application/ports/output/MemberPort.java
> +    Optional<Member> getMemberByKey(String userKey);
매개변수로 들어오는 값이 무엇인지 메서드 명으로 확인할 수 있도록 수정했습니다.

2024-01-24 16:42 UTC, minjinJeong commented on src/main/java/com/flab/funding/domain/model/MemberStatus.java
> +    }
Java Enum 에서 지원해주는 valueOf() 메소드를 사용했습니다.

2024-01-24 16:43 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/input/data/request/MemberCreateRequest.java
> +    private String linkType;
MemberLinkType Enum과 컨버터를 추가했습니다.

2024-01-24 16:45 UTC, minjinJeong commented on src/main/java/com/flab/funding/domain/service/MemberService.java
> +public class MemberService implements CreateMemberUseCase, UpdateMemberUseCase, GetMemberUseCase {
도메인과 어울리는 명칭으로 수정했습니다.
- RegisterMemberUseCase, DeregisterMemberUseCase, LoginUseCase

2024-01-24 16:50 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/entity/MemberEntity.java
> +    @Column(name = "user_key")
JPA Entity에서 DB명과 일치하는 변수 명에는 @Column을 제거했습니다.
- 대문자는 언더스코어( _ ) + 소문자로 자동 변경된다.

2024-01-24 16:50 UTC, merged