[#2] Spring Rest Docs 적용
f-lab-edu/my-crowd-funding pull request #2
Opened 2024-01-30 12:06 UTC by minjinJeong

### 변경 사항
- Spring Rest Docs 적용
- MapStruct 연동

### 이슈
- 테스트를 위한 임시 RepositoryImpl 생성

2024-01-30 14:12 UTC, f-lab-justin requested changes

2024-01-30 14:12 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/input/data/response/MemberCreateResponse.java
> +    private MemberStatus statusCode;
@minjinJeong 
status로 바꿔보시지요~!

2024-01-30 14:12 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/input/rest/MemberRestAdapter.java
> +        return memberMapper.toMemberCreateResponse(member);
@minjinJeong
 생성로직을 해당 클래스 안으로 숨겨주면 추후에 생성로직이 변경되더라도 클라이언트에서의 코드가 바뀌자 않아도 되어서 생성로직 변경에 유연합니다~!

2024-01-30 14:12 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/MemberPersistenceAdapter.java
> +        MemberEntity memberEntity = memberPersistenceMapper.toMemberEntity(member);
@minjinJeong
한번 생각해보셔요~!

```java
MemberEntity memberEntity = MemberEntity.from(member);
MemberEntity savedMemberEntity = memberRepository.save(memberEntity);
return savedMemberEntity.toDomain();
```

2024-01-30 14:12 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/mapper/MemberPersistenceMapper.java
>  public interface MemberPersistenceMapper {
@minjinJeong
역할을 클래스-클래스 이렇게 두개간의 내용들만으로 묶어보면 어떨까요??

2024-02-03 01:04 UTC, f-lab-justin requested changes
@minjinJeong 
[6230cbd](https://github.com/f-lab-edu/my-crowd-funding/pull/2/commits/6230cbd5bf8aacac9a0c0e7cf23d49712d9afcd1) 커밋은 커밋메시지에 오타가 있으니 rebase로 커밋메시지를 바꿔주세요~!

2024-02-03 14:51 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/input/data/response/MemberCreateResponse.java
> +    private MemberStatus statusCode;
사용 용도에 맞게 명칭을 수정했습니다.
- Enum 클래스 안의 코드를 statusCode로 변경
- 외부에서 Enum 명칭(ACTIVATE 등)을 반환할 때는 status로 변경

2024-02-03 14:54 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/input/rest/MemberRestAdapter.java
> +        return memberMapper.toMemberCreateResponse(member);
정적 팩토리 메서드를 만들어, mapper(생성 로직)을 클래스 안으로 숨겨 보았습니다.

2024-02-03 14:55 UTC, minjinJeong commented on src/main/java/com/flab/funding/infrastructure/adapters/output/persistence/MemberPersistenceAdapter.java
> +        MemberEntity memberEntity = memberPersistenceMapper.toMemberEntity(member);
생성 로직을 숨기며 함께 수정했습니다.

2024-02-06 14:15 UTC, f-lab-justin approved these changes
@minjinJeong
수고하셨습니다~ 살짝 살펴보시고 바로 머징가도 될 것 같습니다!

2024-02-06 14:15 UTC, f-lab-justin commented on src/main/java/com/flab/funding/domain/service/MemberService.java
> +        return memberPort.modifyMember(member.deactivate());
@minjinJeong

saveMember로 동일하게 처리하는게 덜 헷갈릴 것 같습니다. 엔티티를 저장한다는 측면에서는 동일한 동작이어서요~!

2024-02-06 14:15 UTC, f-lab-justin commented on src/main/java/com/flab/funding/infrastructure/adapters/input/data/request/MemberCreateRequest.java
>  public class MemberCreateRequest {
@minjinJeong

Create, Regist를 일관되게 사용하면 좀 더 코드를 읽기 용이할 것 같습니다.

2024-02-08 13:33 UTC, merged